---
kind: pipeline
type: docker
name: janus-gateway_test

steps:
  - name: build test
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/janus-gateway
      dry_run: true

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: janus-gateway_build

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "JANUS"
      DOCKERFILE_PATH: "Dockerfile"
      CUSTOM_TAGS: "latest"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/janus-gateway

  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push
