name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "JANUS"
          DOCKERFILE_PATH: "Dockerfile"
          CUSTOM_TAGS: "latest"
          INCLUDE_SUFFIX: "no"
          IMAGE_NAME: "mwalbeck/janus-gateway"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "JANUS"
          DOCKERFILE_PATH: "Dockerfile"
          CUSTOM_TAGS: "latest"
          INCLUDE_SUFFIX: "no"
          IMAGE_NAME: "git.walbeck.it/walbeck-it/janus-gateway"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to forgejo container registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}